app = "stellar-futurenet"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
image = "stellar/quickstart:soroban-dev"

[env]
NETWORK = "futurenet"
ENABLE_SOROBAN_RPC = "true"

[mounts]
source="stellaropt"
destination="/opt/stellar"

[[services]]
internal_port = 8000
processes = ["app"]
protocol = "tcp"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
